import type { Resource, Source } from './types'

/**
 * Shared, checked sources. Each has the date the link and the facts used were last checked.
 * Re-check before reusing a source in a new lesson.
 */
const checked = '2026-09-13'

export const S = {
  // Principles and ethics
  elementsOfJournalism: {
    title: 'The elements of journalism',
    publisher: 'Tom Rosenstiel',
    url: 'https://www.tomrosenstiel.com/essential/the-elements-of-journalism/',
    checked,
  },
  ejnPrinciples: {
    title: 'Who we are: five core principles of journalism',
    publisher: 'Ethical Journalism Network',
    url: 'https://ethicaljournalismnetwork.org/who-we-are',
    checked,
  },
  nigerianCode: {
    title: 'Code of Ethics for Nigerian Journalists',
    publisher: 'Nigerian Press Council',
    url: 'https://presscouncil.gov.ng/code-of-ethics/',
    checked,
  },
  codeAdoption: {
    title: 'An evaluation of conformance to the Code of Ethics (Odionyenma et al., IMSU Journal of Communication Studies, 2024)',
    publisher: 'SSOAR',
    url: 'https://www.ssoar.info/ssoar/bitstream/handle/document/99329/ssoar-imsujcomms-2024-2-odionyenma_et_al-An_evaluation_of_conformance_to.pdf',
    checked,
  },

  // Audiences
  dnrNigeria2026: {
    title: 'Digital News Report 2026: Nigeria',
    publisher: 'Reuters Institute for the Study of Journalism',
    url: 'https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2026/nigeria',
    checked,
  },

  // Nigerian media bodies and outlets
  pressCouncilAbout: {
    title: 'About the Nigerian Press Council',
    publisher: 'Nigerian Press Council',
    url: 'https://presscouncil.gov.ng/who_we_are/',
    checked,
  },
  nbc: {
    title: 'National Broadcasting Commission',
    publisher: 'Wikipedia (the official site nbc.gov.ng was down for maintenance when checked)',
    url: 'https://en.wikipedia.org/wiki/National_Broadcasting_Commission',
    checked,
  },
  nuj: { title: 'Nigeria Union of Journalists', publisher: 'NUJ', url: 'https://nuj.ng/', checked },
  nge: { title: 'About us', publisher: 'Nigerian Guild of Editors', url: 'https://ngeditors.org.ng/about-us/', checked },
  nan: { title: 'About us', publisher: 'News Agency of Nigeria', url: 'https://nannews.ng/about-us/', checked },
  nta: { title: 'NTA', publisher: 'Nigerian Television Authority', url: 'https://www.nta.ng/', checked },
  frcn: { title: 'About us', publisher: 'Radio Nigeria (FRCN)', url: 'https://radionigeria.gov.ng/about-us/', checked },
  von: { title: 'Voice of Nigeria', publisher: 'Voice of Nigeria', url: 'https://von.gov.ng/', checked },
  premiumTimes: { title: 'About us', publisher: 'Premium Times', url: 'https://www.premiumtimesng.com/about', checked },
  dubawa: { title: 'Dubawa', publisher: 'Centre for Journalism Innovation and Development', url: 'https://dubawa.org/', checked },
  factCheckHub: { title: 'About us', publisher: 'FactCheckHub (The ICIR)', url: 'https://factcheckhub.com/about-us/', checked },

  // Newsroom roles
  mhmRoles: {
    title: "Journalism's roles and responsibilities",
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/what-is-a-journalist/',
    checked,
  },
  gouwsRoles: {
    title: 'Journalistic roles in newsrooms (How to be a Journalist in the 21st Century)',
    publisher: 'Gouws et al., North-West University, via LibreTexts',
    url: 'https://socialsci.libretexts.org/Bookshelves/Communication/Journalism_and_Mass_Communication/How_to_be_a_Journalist_in_the_21st_century_(Gouws_et_al.)/04:_The_Work_of_the_Journalist/4.01:_Journalistic_Roles_in_Newsrooms',
    checked,
  },
  pressGazetteJargon: {
    title: 'Journalism jargon guide',
    publisher: 'Press Gazette',
    url: 'https://pressgazette.co.uk/publishers/journalism-jargon-guide/',
    checked,
  },

  // News writing
  harcupONeill2017: {
    title: 'What is news? News values revisited (again). Harcup and O’Neill, Journalism Studies, 2017',
    publisher: 'White Rose Research Online (open access)',
    url: 'https://eprints.whiterose.ac.uk/id/eprint/95423/11/WRRO_95423.pdf',
    checked,
  },
  mhmNewsValue: {
    title: 'How journalists assess news value',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/what-is-news/',
    checked,
  },
  mhmNewsWriting: {
    title: 'Quick guide: news writing',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/quick-guides/quick-guide-news-writing/',
    checked,
  },
  newsManualCh4: {
    title: 'The News Manual, chapter 4: The intro',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://thenewsmanual.net/Manuals%20Volume%201/volume1_04.htm',
    checked,
  },
  owlLeads: {
    title: 'Writing leads',
    publisher: 'Purdue Online Writing Lab',
    url: 'https://owl.purdue.edu/owl/subject_specific_writing/journalism_and_journalistic_writing/writing_leads.html',
    checked,
  },
  owlPyramid: {
    title: 'The inverted pyramid',
    publisher: 'Purdue Online Writing Lab',
    url: 'https://owl.purdue.edu/owl/subject_specific_writing/journalism_and_journalistic_writing/the_inverted_pyramid.html',
    checked,
  },
  mhmStoryElements: {
    title: 'Essential elements of a news story',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/essential-elements-of-a-news-story/',
    checked,
  },
  poynterPyramidHistory: {
    title: 'Birth of the inverted pyramid: a child of technology, commerce and history',
    publisher: 'Poynter (Chip Scanlan, 2003)',
    url: 'https://www.poynter.org/reporting-editing/2003/birth-of-the-inverted-pyramid-a-child-of-technology-commerce-and-history/',
    checked,
  },

  // Structure, quotes and style (Week 3)
  newsManualCh3: {
    title: 'The News Manual, chapter 3: The shape of the news story',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_03.htm',
    checked,
  },
  newsManualCh6: {
    title: 'The News Manual, chapter 6: Writing the news story in simple steps',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_06.htm',
    checked,
  },
  newsManualCh8: {
    title: 'The News Manual, chapter 8: Quotes',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_08.htm',
    checked,
  },
  newsManualCh9: {
    title: 'The News Manual, chapter 9: Attribution',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_09.htm',
    checked,
  },
  zamithQuotes: {
    title: 'The American Journalism Handbook: quotes and attribution',
    publisher: 'Rodrigo Zamith, University of Massachusetts Amherst',
    url: 'https://ajh.rodrigozamith.com/creating-journalistic-content/quotes-and-attribution/',
    checked,
  },
  mhmQuotes: {
    title: 'The power of quotes in journalism',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/the-power-of-quotes-in-journalism/',
    checked,
  },
  mhmAttribution: {
    title: 'Quick guide: attribution in journalism',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/quick-guides/attribution-in-journalism/',
    checked,
  },
  mhmPressReleases: {
    title: 'How to deal with press releases',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/advanced/how-to-deal-with-press-releases/',
    checked,
  },
  reutersStandards: {
    title: 'Standards and values (Reuters Handbook of Journalism)',
    publisher: 'Reuters',
    url: 'https://reutersagency.com/about/standards-values/',
    checked,
  },
  apTellingTheStory: {
    title: 'News values and principles: telling the story',
    publisher: 'Associated Press',
    url: 'https://www.ap.org/about/news-values-and-principles/telling-the-story/',
    checked,
  },
  bbcStyleAll: {
    title: 'BBC News style guide: A to Z',
    publisher: 'BBC',
    url: 'https://www.bbc.co.uk/newsstyleguide/all',
    checked,
  },
  bbcStyleNumbers: {
    title: 'BBC News style guide: numbers',
    publisher: 'BBC',
    url: 'https://www.bbc.co.uk/newsstyleguide/numbers',
    checked,
  },
  bbcStyleNames: {
    title: 'BBC News style guide: names and titles',
    publisher: 'BBC',
    url: 'https://www.bbc.co.uk/newsstyleguide/names',
    checked,
  },
  guardianStyleH: {
    title: 'Guardian style guide: H (including headlines)',
    publisher: 'The Guardian',
    url: 'https://www.theguardian.com/guardian-style-guide-h',
    checked,
  },
  mhmSubEditor: {
    title: 'The sub-editor: roles, skills and responsibilities',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/advanced/the-sub-editor-roles-skills-and-responsibilities/',
    checked,
  },
  cambridgeHeadlines: {
    title: 'Newspaper headlines (English Grammar Today)',
    publisher: 'Cambridge Dictionary',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/newspaper-headlines',
    checked,
  },
  poynterHeadlines: {
    title: '9 tips for writing stronger headlines',
    publisher: 'Poynter',
    url: 'https://www.poynter.org/educators-students/2017/9-tips-for-writing-stronger-headlines/',
    checked,
  },
  premiumTimesExample: {
    title: "Example of house style: Osun's rural PHCs investigation (2 September 2026)",
    publisher: 'Premium Times',
    url: 'https://www.premiumtimesng.com/news/headlines/906906-investigation-despite-billions-of-naira-spent-in-the-health-sector-challenges-remain-in-osuns-rural-phcs.html',
    checked,
  },
  punchExample: {
    title: 'Example of house style: Sowore promises N500,000 wage (13 September 2026)',
    publisher: 'The Punch',
    url: 'https://punchng.com/2027-sowore-promises-n500000-wage-24-hour-electricity-if-elected/',
    checked,
  },

  // Interviewing and sources (Week 4)
  newsManualCh15: {
    title: 'The News Manual, chapter 15: Newsroom books',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_15.htm',
    checked,
  },
  newsManualCh16: {
    title: 'The News Manual, chapter 16: Interviewing basics',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_16.htm',
    checked,
  },
  newsManualCh17: {
    title: 'The News Manual, chapter 17: Telephone interviews',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%201/volume1_17.htm',
    checked,
  },
  newsManualCh59: {
    title: 'The News Manual, chapter 59: Sources of information',
    publisher: 'David Ingram and Peter Henshall',
    url: 'https://www.thenewsmanual.net/Manuals%20Volume%203/volume3_59.htm',
    checked,
  },
  mhmInterviewTips: {
    title: '20 interviewing tips for journalists',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/20-interviewing-tips-for-journalists/',
    checked,
  },
  mhmRemoteInterview: {
    title: 'How to carry out an interview remotely',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/how-to-carry-out-an-interview-remotely/',
    checked,
  },
  mhmOffTheRecord: {
    title: 'Interviewing off the record',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/basics/interviewing-off-the-record/',
    checked,
  },
  poynterInterviewing: {
    title: 'An illustrated guide to the basics of interviewing',
    publisher: 'Poynter',
    url: 'https://www.poynter.org/reporting-editing/2023/illustrated-guide-interviewing-basics-journalism/',
    checked,
  },
  gijnInterviewing: {
    title: 'Introduction to investigative journalism: interviewing techniques for beginners',
    publisher: 'Global Investigative Journalism Network',
    url: 'https://gijn.org/resource/introduction-investigative-journalism-interview-techniques/',
    checked,
  },
  pulseRecordingCalls: {
    title: 'Is it legal to record a phone call without telling the other person?',
    publisher: 'Pulse Nigeria',
    url: 'https://www.pulse.ng/story/is-it-legal-to-record-a-phone-call-without-telling-the-other-person-2025020313422138030',
    checked,
  },
  constitutionS37: {
    title: 'Constitution of Nigeria, section 37 (right to private and family life)',
    publisher: 'Constitute Project',
    url: 'https://www.constituteproject.org/constitution/Nigeria_2011',
    checked,
  },
  childsRightAct: {
    title: "Child's Rights Act 2003 (sections 157 and 277)",
    publisher: 'PLAC Laws of Nigeria',
    url: 'https://placng.org/lawsofnigeria/laws/C50.pdf',
    checked,
  },
  unicefGuidelines: {
    title: 'Ethical reporting guidelines',
    publisher: 'UNICEF',
    url: 'https://www.unicef.org/media/reporting-guidelines',
    checked,
  },
  gcjtVictims: {
    title: 'Ethics and practice: interviewing victims',
    publisher: 'Global Center for Journalism and Trauma (formerly the Dart Center)',
    url: 'https://gcjt.org/content/ethics-and-practice-interviewing-victims',
    checked,
  },
  mhmTrauma: {
    title: 'How to interview trauma survivors',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/advanced/how-to-interview-trauma-survivors/',
    checked,
  },
  iawrtSafety: {
    title: 'What if...? Safety handbook for women journalists',
    publisher: 'International Association of Women in Radio and Television (2017)',
    url: 'https://www.journalism.cuny.edu/wp-content/uploads/2021/12/Safety-Handbook-for-Women-Journalists.pdf',
    checked,
  },
  cpjSources: {
    title: 'Digital and physical safety: protecting confidential sources',
    publisher: 'Committee to Protect Journalists',
    url: 'https://cpj.org/2021/11/digital-physical-safety-protecting-confidential-sources/',
    checked,
  },

  // Ethics (Week 5)
  irbBrownEnvelope: {
    title: 'Nigeria: brown envelope journalism, 2015 to November 2017',
    publisher: 'Immigration and Refugee Board of Canada (via ecoi.net)',
    url: 'https://www.ecoi.net/en/document/1421897.html',
    checked,
  },
  okoroBrownEnvelope: {
    title: "Journalists' perception of brown envelope syndrome (Covenant Journal of Communication, 2013)",
    publisher: 'Covenant University',
    url: 'https://journals.covenantuniversity.edu.ng/index.php/cjoc/article/download/32/28',
    checked,
  },
  skjerdalBrownEnvelopes: {
    title: 'Research on brown envelope journalism in the African media (African Communication Research, 2010)',
    publisher: 'University of KwaZulu-Natal (free PDF of the journal issue)',
    url: 'https://ccms.ukzn.ac.za/Files/articles/ACR/Bribery%20and%20corruption%20in%20African%20journalism.pdf',
    checked,
  },
  ejnNigeria: {
    title: 'Nigeria: calls for ethical revival as corruption infects media (2015)',
    publisher: 'Ethical Journalism Network',
    url: 'https://ethicaljournalismnetwork.org/nigeria',
    checked,
  },
  premiumTimesSalaries: {
    title: 'Nigerian journalists suffer non-payment of salaries (July 2022)',
    publisher: 'Premium Times',
    url: 'https://www.premiumtimesng.com/news/top-news/540978-nigerian-journalists-suffer-non-payment-of-salaries.html',
    checked,
  },
  theCableLeaving: {
    title: "Nigeria's best journalists are leaving, and remuneration isn't the only problem (June 2026)",
    publisher: 'TheCable',
    url: 'https://www.thecable.ng/nigerias-best-journalists-are-leaving-and-remuneration-is-not-the-only-problem/',
    checked,
  },
  peoplesGazettePolicy: {
    title: 'Editorial policy',
    publisher: 'Peoples Gazette',
    url: 'https://gazettengr.com/editorial-policy/',
    checked,
  },
  spjCode: {
    title: 'SPJ Code of Ethics (2014)',
    publisher: 'Society of Professional Journalists',
    url: 'https://spjethics.org/code/',
    checked,
  },
  bbcConflicts: {
    title: 'Editorial guidelines, section 4: conflicts of interest',
    publisher: 'BBC',
    url: 'https://www.bbc.co.uk/editorialguidelines/guidelines/conflicts-of-interest',
    checked,
  },
  guardianCode: {
    title: 'The Guardian’s editorial code',
    publisher: 'The Guardian',
    url: 'https://www.theguardian.com/info/2015/aug/05/the-guardians-editorial-code',
    checked,
  },
  mhmConflicts: {
    title: 'Conflicts of interest',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/ethics/conflicts-of-interest/',
    checked,
  },
  whoSuicide2023: {
    title: 'Preventing suicide: a resource for media professionals (2023 update)',
    publisher: 'World Health Organization and IASP',
    url: 'https://www.who.int/publications/i/item/9789240076846',
    checked,
  },
  attemptedSuicideNigeria: {
    title: 'FG moves to decriminalise attempted suicide, seeks urgent legislative action (September 2026)',
    publisher: 'Peoples Gazette',
    url: 'https://gazettengr.com/fg-moves-to-decriminalise-attempted-suicide-seeks-urgent-legislative-action/',
    checked,
  },
  cjidGbvHandbook: {
    title: 'Gender-based violence reporting handbook (2022)',
    publisher: 'Centre for Journalism Innovation and Development (CJID)',
    url: 'https://thecjid.org/wp-content/uploads/2022/03/Gender-Based-Violence-Reporting-Handbook.pdf',
    checked,
  },
  ejnHateSpeechTest: {
    title: 'Hate speech: a 5-point test for journalists',
    publisher: 'Ethical Journalism Network',
    url: 'https://ethicaljournalismnetwork.org/hate-speech-a-5-point-test-for-journalists',
    checked,
  },
  ipcElectionCode: {
    title: 'Nigerian Media Code of Election Coverage (revised 2018)',
    publisher: 'International Press Centre',
    url: 'https://www.ipcng.org/wp-content/uploads/2018/06/The-Nigerian-Media-Code-of-Election-Coverage-2018.pdf',
    checked,
  },
  gijnEthnoReligious: {
    title: 'Tips for investigating and reporting on ethno-religious conflicts responsibly and ethically',
    publisher: 'Global Investigative Journalism Network',
    url: 'https://gijn.org/stories/tips-reporting-ethno-religious-conflicts-responsibly-ethically/',
    checked,
  },
  theCableCorrections: {
    title: 'Correction policy (January 2025)',
    publisher: 'TheCable',
    url: 'https://www.thecable.ng/correction-policy/',
    checked,
  },
  apiCorrections: {
    title: 'How to correct website and social media errors effectively',
    publisher: 'American Press Institute (Craig Silverman, 2014)',
    url: 'https://americanpressinstitute.org/digital-corrections/',
    checked,
  },
  gusauJudgment: {
    title: 'Gusau v The Guardian Newspaper Ltd, Suit CV/2077/2020 (judgment, 2024)',
    publisher: 'High Court of the Federal Capital Territory',
    url: 'https://www.fcthighcourt.gov.ng/wp-content/uploads/2025/02/HON-ENGR-IBRAHIM-SHEHU-GUSAU-PHD-VS.-THE-GUARDIAN-NEWSPAPER-LTD-TORT-LIBEL.pdf',
    checked,
  },
  cjrRollingStone: {
    title: "Rolling Stone's investigation: 'A failure that was avoidable' (April 2015)",
    publisher: 'Columbia Journalism Review',
    url: 'https://www.cjr.org/investigation/rolling_stone_investigation.php',
    checked,
  },
  nprRollingStoneVerdict: {
    title: 'Jury awards University of Virginia official $3 million in Rolling Stone suit (November 2016)',
    publisher: 'NPR',
    url: 'https://www.npr.org/sections/thetwo-way/2016/11/07/501090618/jurors-award-3-million-in-damages-in-defamation-suit-against-rolling-stone',
    checked,
  },
  sundayTimesApology: {
    title: 'Sunday Times editor: we got it wrong, and for that we apologise (October 2018)',
    publisher: 'The Media Online',
    url: 'https://themediaonline.co.za/2018/10/sunday-times-editor-we-got-it-wrong-and-for-that-we-apologise/',
    checked,
  },

  // Media law (Week 6)
  constitution: {
    title: 'Constitution of the Federal Republic of Nigeria 1999 (as amended)',
    publisher: 'National Human Rights Commission (nigeriarights.gov.ng)',
    url: 'https://nigeriarights.gov.ng/files/constitution.pdf',
    checked,
  },
  chapterTwoEnforceability: {
    title: 'The enforceability of Chapter 2 of the 1999 Constitution',
    publisher: 'BarristerNG (J.A. Ndu, 2021)',
    url: 'https://barristerng.com/the-enforceability-of-chapter-2-of-the-1999-constitution-of-federal-republic-of-nigeria/',
    checked,
  },
  rsfNigeria: {
    title: 'Nigeria country page, World Press Freedom Index 2026',
    publisher: 'Reporters Without Borders (RSF)',
    url: 'https://rsf.org/en/country/nigeria',
    checked,
  },
  cpjTinubuTenure: {
    title: "Tracking Tinubu's tenure: CPJ exposes Nigeria's media repression reality (May 2026)",
    publisher: 'Committee to Protect Journalists',
    url: 'https://cpj.org/2026/05/tracking-tinubus-tenure-cpj-exposes-nigerias-media-repression-reality/',
    checked,
  },
  criminalCode: {
    title: 'Criminal Code Act, Cap C38 (sections 133, 373 to 381)',
    publisher: 'PLAC Laws of Nigeria',
    url: 'http://lawsofnigeria.placng.org/laws/C38.pdf',
    checked,
  },
  penalCode: {
    title: 'Penal Code (Northern States) Federal Provisions Act (sections 391 to 395)',
    publisher: 'ILGA legal database copy',
    url: 'https://database.ilga.org/api/downloader/download/1/NG%20-%20LEG%20-%20Penal%20Code%20(Northern%20States)%20Federal%20Provisions%20Act%20(1959)%20-%20OR(en).pdf',
    checked,
  },
  lagosCriminalLaw: {
    title: 'Criminal Law of Lagos State 2011',
    publisher: 'Lagos State (copy on SourceAfrica)',
    url: 'https://s3-eu-west-1.amazonaws.com/s3.sourceafrica.net/documents/120445/Criminal-Law-of-Lagos-State.pdf',
    checked,
  },
  nbaLibel: {
    title: 'Libel is not a crime: NBA calls for immediate release of Dele Farotimi (December 2024)',
    publisher: 'Nigerian Bar Association',
    url: 'https://blog.nigerianbar.org.ng/2024/12/03/libel-is-not-a-crime-nba-calls-for-immediate-release-of-dele-farotimi/',
    checked,
  },
  carterRuckNigeria: {
    title: 'Nigeria media law guide (June 2026)',
    publisher: 'Carter-Ruck',
    url: 'https://www.carter-ruck.com/law-guides/nigeria-2/',
    checked,
  },
  foiAct: {
    title: 'Freedom of Information Act 2011 (Official Gazette No. 36, Vol. 98)',
    publisher: 'Federal Republic of Nigeria (Gazettes.Africa archive)',
    url: 'https://archive.gazettes.africa/archive/ng/2011/ng-government-gazette-dated-2011-05-30-no-36.pdf',
    checked,
  },
  foiSupremeCourt: {
    title: 'FOI Act applicable to 36 states, Supreme Court rules (April 2025)',
    publisher: 'Premium Times',
    url: 'https://www.premiumtimesng.com/news/787268-freedom-of-information-foi-act-applicable-to-36-states-supreme-court-rules.html',
    checked,
  },
  cybercrimesAct2015: {
    title: 'Cybercrimes (Prohibition, Prevention, etc.) Act 2015',
    publisher: 'Nigerian Financial Intelligence Unit (copy)',
    url: 'https://www.nfiu.gov.ng/images/Downloads/downloads/cybercrime.pdf',
    checked,
  },
  cybercrimesAmendment: {
    title: 'Coalition lauds Cybercrimes Act amendment and urges further safeguards (March 2024)',
    publisher: 'Paradigm Initiative',
    url: 'https://paradigmhq.org/press-release-coalition-lauds-cybercrimes-act-amendment-and-urges-fg-to-further-safeguard-freedom-of-expression/',
    checked,
  },
  cpjCybercrimes2025: {
    title: '3 Nigerian journalists detained on cybercrime allegations despite reform (November 2025)',
    publisher: 'Committee to Protect Journalists',
    url: 'https://cpj.org/2025/11/3-nigerian-journalists-detained-on-cybercrime-allegations-despite-reform/',
    checked,
  },
  cpjSixthJournalist: {
    title: 'Nigerian authorities detain another journalist for cybercrimes over governance reports (November 2025)',
    publisher: 'Committee to Protect Journalists',
    url: 'https://cpj.org/2025/11/nigerian-authorities-detain-another-journalist-for-cybercrimes-over-governance-reports/',
    checked,
  },
  aviomoh: {
    title: 'Aviomoh v COP & Anor (Supreme Court, 2021): case summary',
    publisher: 'LawCare Nigeria',
    url: 'https://lawcarenigeria.com/aviomoh-v-c-o-p-anor-2021/',
    checked,
  },
  ecowasCybercrimes: {
    title: 'Obey ECOWAS judgment on section 24 of the Cybercrime Act (April 2022)',
    publisher: 'SERAP',
    url: 'https://serap-nigeria.org/2022/04/03/obey-ecowas-judgment-end-prosecutions-for-insulting-public-officials-serap-tells-buhari/',
    checked,
  },
  copyrightAct: {
    title: 'Copyright Act 2022 (section 20, fair dealing)',
    publisher: 'Nigerian Copyright Commission',
    url: 'https://www.copyright.gov.ng/CopyrightAct/CopyrightAct2023FinalPublication1.pdf',
    checked,
  },
  ndpaExplained: {
    title: "Nigeria's new Data Protection Act, explained (June 2023)",
    publisher: 'Future of Privacy Forum',
    url: 'https://fpf.org/blog/nigerias-new-data-protection-act-explained/',
    checked,
  },
  ndpaText: {
    title: 'Nigeria Data Protection Act 2023 (section 3)',
    publisher: 'Nigeria Data Protection Commission',
    url: 'https://ndpc.gov.ng/download/nigeria-data-protection-act-2023',
    checked,
  },
  officialSecretsAct: {
    title: 'Official Secrets Act, Cap O3',
    publisher: 'PLAC Laws of Nigeria',
    url: 'https://www.placng.org/lawsofnigeria/print.php?sn=421',
    checked,
  },
  nbcFinesAppeal: {
    title: "Appeal court affirms dismissal of NBC's fines against 45 broadcast stations (April 2026)",
    publisher: 'Premium Times',
    url: 'https://www.premiumtimesng.com/news/top-news/868937-appeal-court-affirms-dismissal-of-nbcs-fines-against-45-broadcast-stations.html',
    checked,
  },
} satisfies Record<string, Source>

export const R = {
  gniFundamentals: {
    title: 'Fundamentals',
    publisher: 'Google News Initiative',
    url: 'https://newsinitiative.withgoogle.com/resources/trainings/fundamentals/',
    checked,
    kind: 'course',
    minutes: 75,
    note: 'Eleven short lessons on search and digital tools for journalists. Free, and works in a tablet browser.',
  },
  dnrNigeria: {
    ...S.dnrNigeria2026,
    kind: 'article',
    minutes: 15,
    note: 'The full Nigeria page from this year’s report. Read it after the lesson on how news reaches people.',
  },
  nigerianCode: {
    ...S.nigerianCode,
    kind: 'guide',
    minutes: 20,
    note: 'The full code. Skim the 15 article headings now. You will study it closely in Week 5.',
  },
  mhmModule: {
    title: 'Module: news reporting and production',
    publisher: 'Media Helping Media',
    url: 'https://mediahelpingmedia.org/modules/module-news-reporting-and-production/',
    checked,
    kind: 'course',
    note: 'Free, short, plain-English lessons on news writing. Good extra practice for this week.',
  },
  newsManualCh4: {
    ...S.newsManualCh4,
    kind: 'guide',
    minutes: 25,
    note: 'A free chapter on writing intros, written for journalists in developing countries.',
  },
  newsManualQuotes: {
    ...S.newsManualCh8,
    kind: 'guide',
    minutes: 15,
    note: 'Clear rules on direct, partial and reported quotes, with worked examples. Read chapter 9 on attribution next.',
  },
  poynterHeadlines: {
    ...S.poynterHeadlines,
    kind: 'article',
    minutes: 3,
    note: 'A short, practical list of headline tips that puts accuracy first.',
  },
  bbcStyleGuide: {
    title: 'BBC News style guide',
    publisher: 'BBC',
    url: 'https://www.bbc.co.uk/newsstyleguide',
    checked,
    kind: 'guide',
    note: 'A free, searchable style guide. Useful when your newsroom has no guide of its own.',
  },
  mhmRemoteInterview: {
    ...S.mhmRemoteInterview,
    kind: 'article',
    minutes: 17,
    note: 'Pros and cons of interviewing by phone, messaging apps, email and video.',
  },
  gijnInterviewing: {
    ...S.gijnInterviewing,
    kind: 'article',
    minutes: 15,
    note: 'Interviewing tips from a Senegalese investigative journalist, including consent and off-the-record rules.',
  },
  iawrtSafety: {
    ...S.iawrtSafety,
    kind: 'guide',
    minutes: 40,
    note: 'A practical safety handbook written for women journalists. Read the section on meeting sources.',
  },
  ejnHateSpeechVideo: {
    title: 'Ethics 101: the EJN 5-point test for hate speech',
    publisher: 'Ethical Journalism Network (YouTube)',
    url: 'https://www.youtube.com/watch?v=TNktlh0ajAo',
    checked,
    kind: 'video',
    minutes: 3,
    note: 'A two-minute video on deciding whether to report inflammatory speech. Useful for politics reporting.',
  },
  cjidGbvHandbook: {
    ...S.cjidGbvHandbook,
    kind: 'guide',
    note: 'A Nigerian handbook on reporting gender-based violence. Start with the chapter on ethics, not the whole book.',
  },
  whoSuicide: {
    ...S.whoSuicide2023,
    kind: 'guide',
    minutes: 30,
    note: 'The current WHO guide for journalists on reporting suicide safely. Read the quick reference page first.',
  },
  foiActText: {
    ...S.foiAct,
    kind: 'guide',
    minutes: 30,
    note: 'The full FOI Act as published in the government gazette. Sections 1 to 8 cover how requests work.',
  },
  carterRuck: {
    ...S.carterRuckNigeria,
    kind: 'guide',
    minutes: 30,
    note: 'A plain overview of Nigerian media law by lawyers. Read it with care: one point on Penal Code sentences is out of line with the law’s text.',
  },
  mraPublications: {
    title: 'Publications, including a citizens’ guide to the FOI Act',
    publisher: 'Media Rights Agenda',
    url: 'https://mediarightsagenda.org/publications-produced-by-media-rights-agenda/',
    checked,
    kind: 'guide',
    note: 'Nigerian press freedom group with guides on using the FOI Act.',
  },
} satisfies Record<string, Resource>
